# Generated by Django 6.0.5 on 2026-06-02 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('oil', 'Oil change'), ('inspection', 'Inspection'), ('brakes', 'Brakes'), ('other', 'Other')], default='other', max_length=32)),
                ('date', models.DateField()),
                ('odometer_km', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='garage.car')),
            ],
            options={
                'ordering': ['-date', '-odometer_km', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('oil', 'Oil change'), ('inspection', 'Inspection'), ('brakes', 'Brakes'), ('other', 'Other')], max_length=32)),
                ('interval_km', models.PositiveIntegerField(default=10000)),
                ('last_done_km', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='garage.car')),
            ],
            options={
                'unique_together': {('car', 'service_type')},
            },
        ),
    ]
